[package]
name = "sakurs-py"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Python bindings for Sakurs sentence boundary detection"

[lib]
name = "sakurs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20", features = ["extension-module"] }
sakurs-core = { path = "../sakurs-core" }
thiserror = { workspace = true }