[metadata]
code = "en"
name = "English"

[terminators]
chars = [".", "!", "?"]

# Limited pattern recognition for special cases
patterns = [
    { pattern = "!?", name = "surprised_question" },
    { pattern = "?!", name = "questioning_exclamation" }
]

[ellipsis]
# Default behavior: treat as boundary
treat_as_boundary = true
patterns = ["...", "…"]

# Context-based rules
context_rules = [
    { condition = "followed_by_capital", boundary = true },
    { condition = "followed_by_lowercase", boundary = false }
]

# Exception patterns (regex)
exceptions = [
    { regex = "\\b(um|uh|er)\\.\\.\\.", boundary = false }
]

[enclosures]
# Pairs are assigned IDs automatically based on array order
pairs = [
    { open = "(", close = ")" },
    { open = "[", close = "]" },
    { open = "{", close = "}" },
    { open = "'", close = "'", symmetric = true },
    { open = '"', close = '"', symmetric = true }
]

[suppression]
# Fast pattern matching for enclosure suppression
fast_patterns = [
    { char = "'", before = "alpha", after = "alpha" },
    { char = ")", line_start = true, before = "alnum" }
]

[abbreviations]
# Organized by category for maintainability
titles = [
    "Dr", "Prof", "Mr", "Mrs", "Ms", "Jr", "Sr"
    # TODO: These contain periods and need special handling
    # "Ph.D", "M.D", "B.A", "M.A", "B.S", "M.S"
]

academic = [
    "Ph.D", "M.D", "B.A", "M.A", "B.S", "M.S", "LL.B", "LL.M", "J.D", "D.D.S", "D.V.M"
]

business = [
    "Inc", "Corp", "Ltd", "LLC", "Co", "L.P", "L.L.C", "P.C", "N.A"
]

time = [
    "a.m", "p.m", "A.M", "P.M"
]

geographic = [
    "U.S", "U.K", "U.S.A", "U.K", "E.U", "U.N",
    # Note: Added back St with specific common usage pattern to avoid false matches
    "St", "Ave", "Blvd", "Pkwy",
    # TODO: These short abbreviations need word boundary checking
    # "Rd", "Dr", "Ct", "Ln", "Sq", "Pl", "Mt", "Ft", "Is", "Pt"
]

common = [
    "etc", "vs", "e.g", "i.e", "cf", "al", "seq", "no", "No", "vol", "Vol",
    # TODO: Single letter and short abbreviations need word boundary checking
    # "v", "pp", "p", "ed", "Ed", "trans", "Trans", "ca", "c", "esp", "viz"
]

measurement = [
    "oz", "lb", "lbs", "kg", "mg", "km", "cm", "mm", "ft", "yd",
    "mi", "hr", "min", "sec", "mph", "kph", "°F", "°C"
    # TODO: Single letter abbreviations need word boundary checking
    # "g", "m", "in"
]

month = [
    "Jan", "Feb", "Mar", "Apr", "Jun", "Jul", "Aug", "Sep", "Sept", "Oct", "Nov", "Dec"
]

military = [
    "Gen", "Col", "Maj", "Capt", "Lt", "Sgt", "Cpl", "Pvt", "Adm"
]